Added a test to the CI to try and avoid breaking the PyPI install test inadvertently again.
